package it.unical.pizzamanager.persistence.dto;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

@Entity
@Table(name = "users")
@SequenceGenerator(name = "usersGenerator", sequenceName = "usersSequence", initialValue = 1)
public class User implements Serializable {

	private static final long serialVersionUID = -3757655889200619517L;

	private static final int NO_ID = -1;

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "usersGenerator")
	@Column(name = "id")
	private Integer id;

	@Column(name = "email", length = 255, unique = true, nullable = false)
	private String email;

	@Column(name = "password", length = 255, unique = true, nullable = false)
	private String password;

	@Column(name = "userName", length = 255, unique = true, nullable = false)
	private String userName;
	
	public User() {
		this.id = NO_ID;
		this.email = "";
		this.password = "";
		this.userName="";
	}

	/*
	 * This constructor doesn't need to set an id since it will be automatically generated by the
	 * DBMS.
	 */
	public User(String email, String password,String userName) {
		this.id = NO_ID;
		this.email = email;
		this.password = password;
		this.userName= userName;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Override
	public String toString() {
		return "User " + id + ": email = " + email + ", password = " + password;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}
}